apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xuanji.fullname" . }}-helm-wrapper-configmap
  labels:
    {{- include "xuanji.labels" . | nindent 4 }}
data:
  config: |
    uploadPath: /tmp/charts
{{ if gt (len .Values.helmWrapper.helmRepos) 0 }}
    helmRepos:
  {{- range .Values.helmWrapper.helmRepos }}
      - name: {{ .name }}
        url: {{ default "http://chartmuseum-chartmuseum.default.svc.cluster.local:8080" .url }}
  {{- end -}}
{{- end }}