apiVersion: v1
kind: Service
metadata:
  name: {{ include "xuanji.fullname" . }}-helm-warpper
  labels:
    {{- include "xuanji.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: helm-wrapper
    {{- include "xuanji.selectorLabels" . | nindent 4 }}
