apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: xuanji
  labels:
    {{- include "xuanji.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xuanji
subjects:
  - kind: ServiceAccount
    name: xuanji
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "xuanji.labels" . | nindent 4 }}
  name: xuanji
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "ingresses", "nodes", "deployments", "namespaces", "pods/log", "pods/status"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces", "secrets"]
    verbs: ["create", "update", "patch", "delete"]
