apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xuanji.fullname" . }}-ws
  labels:
    app: ws
    {{- include "xuanji.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws
      {{- include "xuanji.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ws
        {{- include "xuanji.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: terminal-ws
      containers:
        - name: ws-app
          image: "{{ .Values.ws.image.repository }}:{{ .Values.ws.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http