helmWrapper:
  image:
    repository: duccnzj/helm
    tag: "v8"

ws:
  helmRepoUrl: "http://chartmuseum-chartmuseum.default.svc.cluster.local:8080"
  image:
    repository: duccnzj/ws
    tag: "v3"
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations: 
      # cert-manager.io/cluster-issuer: "letsencrypt-prod"
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: []
      # - ws.web.local
    tls: []

replicaCount: 1

image:
  repository: duccnzj/xuanji
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v12"

imagePullSecrets: []

service:
  type: ClusterIP

ingress:
  enabled: false
  annotations: 
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
  tls: []

config: {}
  # APP_NAME:
  # APP_KEY
  # DB_HOST:
  # DB_PORT:
  # DB_DATABASE:
  # DB_USERNAME:
  # DB_PASSWORD:
  # SSO_ENABLED:
  # SSO_BASE_URL:
  # GITLAB_URL:
  # GITLAB_TOKEN:
  # MIX_SHELL_SOCKET_URL:
  # WILDCARD_DOMAIN:
  # DOCKER_USERNAME:
  # DOCKER_PASSWORD:
  # DOCKER_SERVER: