helmWrapper:
  helmRepos: []
    # - name: xuanji
    #   url: http://chartmuseum-chartmuseum.default.svc.cluster.local:8080
  image:
    repository: duccnzj/helm
    tag: "v8"

ws:
  image:
    repository: duccnzj/ws
    tag: "v3"
  service:
    type: ClusterIP
    nodePort: 32222
  ingress:
    enabled: false
    annotations: {}
      # cert-manager.io/cluster-issuer: "letsencrypt-prod"
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: []
    #   - ws.example.com
    tls: []
    # - secretName: ws-tls
    #   hosts:
    #     - ws.example.com

image:
  repository: duccnzj/xuanji
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v18"

imagePullSecrets: []

service:
  type: ClusterIP
  nodePort: 32221

ingress:
  enabled: false
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
  #   - xuanji.example.com
  tls: []
  # - secretName: xuanji-tls
  #   hosts:
  #     - xuanji.example.com

config: {}
  # 默认“玄机”
  # APP_NAME:
  # DB_HOST:
  # DB_PORT:
  # DB_DATABASE:
  # DB_USERNAME:
  # DB_PASSWORD:

  # 是否开启sso, 默认 false
  # SSO_ENABLED:
  # SSO_BASE_URL:

  # GITLAB_URL:
  # GITLAB_TOKEN:

  # MIX_SHELL_SOCKET_URL:
  # WILDCARD_DOMAIN:

  # echo "${docker_username}|${docker_password}" | base64
  # DOCKER_AUTH:
  # DOCKER_SERVER:

  # 没有外网ip时需要提供
  # CLUSTER_IP:

  # CLUSTER_ISSUER:

  # k8s namespace prefix
  # MIX_NS_PREFIX: devops-